### ISSUE TITLE
Fix crash when generating server certificate

### ISSUE THREAD

**Issue by J-Javan** [MDTech-us-MAN/SSNFS#22]
Server crashes when generating certificate. 

Environment:
* Ubuntu 18.04.1 LTS
* libssl1.0-dev version: 1.0.2n-1ubuntu5.1
* openssl1.0 version: 1.0.2n-1ubuntu5.1
* Qt version: 5.10.1

To reproduce run:
$ path/to/SSNFSd --init

![ssnfsd_crash](https://user-images.githubusercontent.com/2700255/45112525-1e1b9880-b15d-11e8-9a12-d41960d73de9.png)

**Comment by J-Javan** [comment]
This bug has been fixed in issue #23.

**Comment by Maxwell175** [comment]
Thank you for your contribution.
